// Auto-generated by Riyo from riyo.content.yaml — do not edit directly.
import { defineCollection, z } from "astro:content";
import { glob } from "astro/loaders";

const banners = defineCollection({
  loader: glob({ base: "./src/content/banners", pattern: "**/*.{md,mdx}" }),
  schema: z.object({
    title: z.string(),
    banner: z.string(),
    link: z.string().optional(),
    published: z.boolean().optional(),
  }),
});

const contributors = defineCollection({
  loader: glob({ base: "./src/content/contributors", pattern: "**/*.{md,mdx}" }),
  schema: z.object({
    title: z.string(),
    name: z.string(),
    nameJa: z.string().optional(),
    profilePicture: z.string().optional(),
    role: z.string(),
    showDetails: z.boolean().optional(),
    publications: z.array(z.string()).optional(),
    published: z.boolean().optional(),
  }),
});

const publications = defineCollection({
  loader: glob({ base: "./src/content/publications", pattern: "**/*.{md,mdx}" }),
  schema: z.object({
    title: z.string(),
    titleJa: z.string(),
    coverSmall: z.string().optional(),
    author: z.string().optional(),
    contributors: z.array(z.string()).optional(),
    storeLinks: z.array(z.object({
        linkText: z.string(),
        linkUrl: z.string(),
      })),
    defaultStoreLink: z.string().optional(),
    notPublished: z.boolean().optional(),
    toeicRangeLow: z.string().optional(),
    toeicRangeHigh: z.string().optional(),
    eikenRangeLow: z.string().optional(),
    eikenRangeHigh: z.string().optional(),
    publicationDate: z.string().optional(),
    published: z.boolean().optional(),
  }),
});

const series = defineCollection({
  loader: glob({ base: "./src/content/series", pattern: "**/*.{md,mdx}" }),
  schema: z.object({
    title: z.string(),
    bannerSmall: z.string().optional(),
    seriesLogo: z.string().optional(),
    entries: z.array(z.string()),
    published: z.boolean().optional(),
  }),
});

const updates = defineCollection({
  loader: glob({ base: "./src/content/updates", pattern: "**/*.{md,mdx}" }),
  schema: z.object({
    title: z.string(),
    icon: z.string(),
    date: z.string(),
    link: z.string().optional(),
    published: z.boolean().optional(),
  }),
});

export const collections = {
  banners,
  contributors,
  publications,
  series,
  updates,
};
